export const FETCH_MARKDOWN_FILES_SUCCESS = 'FETCH_MARKDOWN_FILES_SUCCESS';
export const FETCH_MARKDOWN_FILES_FAILURE = 'FETCH_MARKDOWN_FILES_FAILURE';
export const CREATE_MARKDOWN_FILE_FAILURE = 'CREATE_MARKDOWN_FILE_FAILURE';
export const CREATE_MARKDOWN_FILE_SUCCESS = 'CREATE_MARKDOWN_FILE_SUCCESS';
export const EDIT_MARKDOWN_FILE_FAILURE = 'EDIT_MARKDOWN_FILE_FAILURE';
export const EDIT_MARKDOWN_FILE_SUCCESS = 'EDIT_MARKDOWN_FILE_SUCCESS';
export const DELETE_MARKDOWN_FILE_FAILURE = 'DELETE_MARKDOWN_FILE_FAILURE';
export const DELETE_MARKDOWN_FILE_SUCCESS = 'DELETE_MARKDOWN_FILE_SUCCESS';