export const FETCH_MARKDOWN_FILES_SUCCESS = 'FETCH_MARKDOWN_FILES_SUCCESS';
export const FETCH_MARKDOWN_FILES_FAILURE = 'FETCH_MARKDOWN_FILES_FAILURE';
export const CREATE_MARKDOWN_FILE_FAILURE = 'CREATE_MARKDOWN_FILE_FAILURE';
export const CREATE_MARKDOWN_FILE_SUCCESS = 'CREATE_MARKDOWN_FILE_SUCCESS';